"""Compatibility shim — re-exports from src.tasks.core.types.

All TypedDict result definitions live in src/tasks/core/types.py.
Import from ``src.tasks.core`` or ``src.tasks`` for the public API.
"""
from __future__ import annotations

from src.tasks.core.types import (  # noqa: F401 — re-exports
    AntiPatternFinding,
    AntiPatternResult,
    DependencyEdge,
    DependencyGraphResult,
    DuplicateBlock,
    DuplicationFinding,
    DuplicationResult,
    HealthDetails,
    HealthResult,
    ImpactAnalysisResult,
    KnowledgeEdge,
    KnowledgeGraphResult,
    KnowledgeNode,
    PatternDetail,
    PatternDetectionResult,
    RoadmapItem,
    SecurityFinding,
    SecurityHeuristicsResult,
    SemanticDuplicateOccurrence,
    SemanticDuplicationFinding,
    SemanticDuplicationResult,
    SilentFailureFinding,
    SilentFailureResult,
    StructureResult,
    SynthesisRoadmapResult,
    TechStackResult,
    TestMappingResult,
    VulnerabilityResult,
)

__all__ = [
    "AntiPatternFinding",
    "AntiPatternResult",
    "DependencyEdge",
    "DependencyGraphResult",
    "DuplicateBlock",
    "DuplicationFinding",
    "DuplicationResult",
    "HealthDetails",
    "HealthResult",
    "ImpactAnalysisResult",
    "KnowledgeEdge",
    "KnowledgeGraphResult",
    "KnowledgeNode",
    "PatternDetail",
    "PatternDetectionResult",
    "RoadmapItem",
    "SecurityFinding",
    "SecurityHeuristicsResult",
    "SemanticDuplicateOccurrence",
    "SemanticDuplicationFinding",
    "SemanticDuplicationResult",
    "SilentFailureFinding",
    "SilentFailureResult",
    "StructureResult",
    "SynthesisRoadmapResult",
    "TechStackResult",
    "TestMappingResult",
    "VulnerabilityResult",
]
